apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: dXNlcg==      # base64 encoded 'user'
  postgres-password: cGFzc3dvcmQ=  # base64 encoded 'password'
